### ISSUE TITLE
shutdown broken too

### ISSUE THREAD

**Issue by pisto** [online-labs/image-fedora#17]
Shutting down causes kernel panic, something related to ext4 that cannot write to the nbd device. Notably it happens after systemd prints "reached target shutdown"

**Comment by moul** [comment]
Thank you @pisto 

I think it's directly related to #15 and I'm working on it today :)

I will try to make the shutdown more clean, but I have to admit that my priority is about reboot, since a shutdown will only let you the options to ask for an electrical power-off or powercycle from the web console

But kernel panics are ugly and under certain circonstances we could lost some data if a software try to close nicely, i.e databases maybe

I will update the #15 issue first, then check if my fixes are compatible with #17

**Comment by pisto** [comment]
There is actualy data loss. My .bash_history of user root consistently gets binary garbage in it at every shutdown/reboot.

**Comment by moul** [comment]
ok, so more blocking than I thought
coming back to you

**Comment by pisto** [comment]
Is it possible that the initrd you have can run a fsck in case of a dirty shutdown before it boots systemd on the instance? Because that would explain the massive boot delay I had after rebooting yesterday night: as I said I do get file corruption, and if fsck sees that and trigger itself this would explain the 20 minutes boot I had.

**Comment by moul** [comment]
In the current initrd, we don't run fsck manually but from what I think, the ext4 kernel module may do it by itself
If you have the opportunity the next time, open the serial tool in the web console, you will see boot process

I need to improve the initrd/systemd support today and will give a look to kernel internals for fsck
A related issue exists here: https://github.com/online-labs/initrd/issues/13, I will comment out to improve the study of current kernel behavior

**Comment by pisto** [comment]
I tried to access the console, it didn't show anything.

**Comment by pisto** [comment]
here's an excerpt of dmesg

[   10.224044] C1 Online: initializing
[   10.293899] C1 Online: initialized
[   13.420985] udev[1047]: starting version 164
[  287.294667] random: nonblocking pool is initialized
[ 1084.183949] EXT4-fs (nbd0): INFO: recovery required on readonly filesystem
[ 1084.268997] EXT4-fs (nbd0): write access will be enabled during recovery
[ 1087.116634] EXT4-fs (nbd0): recovery complete
[ 1087.170768] EXT4-fs (nbd0): mounted filesystem with ordered data mode. Opts: (null)
[ 1087.702984] systemd[1]: systemd 216 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)

**Comment by moul** [comment]
for the console, we hot connect on the hardware serial (/dev/tty0) without the line history (we are working on a buffer proxy to handle this)

if your server is booting, the kernel, initrd and systemd are printing a lot of messages you can see without doing anything else, but if your server is already booted, you should have very few if not zero printed lines on tty0, so you need to type on [enter] to get a login shell

It's a little bit annoying, sorry :/

---

ok so it confirms that the fsck (recovery here) was done automatically by the kernel, but the timestamp on the left looks strange, I expect the `[ 1084.183949] EXT4-fs (nbd0): INFO: recovery required on readonly filesystem` to be a lot sooner

**Comment by pisto** [comment]
I know that I have to "nudge" the console with a few enters, and that didn't help.

**Comment by moul** [comment]
If you have ssh access, can you give me the result of `lsmod` please ?

**Comment by pisto** [comment]
```
[root@pisto-horse ~]# lsmod 
Module                  Size  Used by
ipv6                  277312  14 
nolp                    1466  0 
```
I was wondering already why it shows only these.

**Comment by moul** [comment]
The `nolp` kernel module let the serial multiplexer be aware that the node is ready, since it is loaded, the issue is not coming from the node
I just tried on the pisto.horse server and got this:
```
pisto-horse login:                                                                                                                                                                                                      
Fedora release 21 (Twenty One)                                                                                                                                                                                          
Kernel 3.18.6-155 on an armv7l (ttyS0)                                                                                                                                                                                                                                                                                                                                                                                                      
```

I hope it works for you too and that it was a temporary failure, else, can you open a ticket on the web console so we can keep this github issue targetted on the shutdown issue ?  I'm also on IRC (`moul`) if you want to pv me :)

---

About your wondering, most of the required modules are built monolithically with the kernel (nbd, ext4, console, ip-pnp, marvell vendor modules, ...)
https://github.com/online-labs/kernel-config/blob/master/3.17.8-std/.config#L2937
So on fresh start without plenty of services, your lsmod should looks very small, no worries

**Comment by aimxhaisse** [comment]
@moul Aren't these 20 minutes the time required to download the volume on a new instance?

**Comment by pisto** [comment]
while it was waiting the web interface state was "started kernel" (oslt).

**Comment by moul** [comment]
Yes nice point, I really need to give further investigations on this part

**Comment by aimxhaisse** [comment]
@pisto I've checked the booting logs of your instance on our side, the volume (17GO) was downloaded to your current running instance between Feb 19, 2015 12:58:42 AM and Feb 19, 2015 1:16:19 AM, I think that matches the long time of boot you encountered.

**Comment by pisto** [comment]
ok. Is it expected that the transmission speed is only 150Mbit/s? Don't instance have supposedly a 1Gbit/s link?

**Comment by aimxhaisse** [comment]
Yes it is expected. That's not only bound to the network speed actually, but also to the I/Os of the machine that serves your volume via NBD, its current load, as well as the time required to perform some integrity checks on the volume once received. It's an area we are working on, so it's likely to perform better in a near future.

**Comment by pisto** [comment]
Yes that would be appreciated. I shiver at the idea of multiple volumes transferred on every cold boot at that speed.
